<?php

return [
    'categories_title'       => 'Kosher Food Categories - KosherMap',
    'categories_description' => 'Explore all kosher food categories: dairy, meat, beverages, bakery, snacks and more. Each category includes products certified by the world\'s leading kosher agencies.',
    'categories_intro_1'     => 'KosherMap organizes its catalog of over 6,000 kosher products into categories and subcategories to make your search easier. Find certified foods by category: from dairy and meat to bakery, beverages, snacks and cleaning products.',
    'categories_intro_2'     => 'Each category shows the certifier\'s seal (OU, KMD, Ajdut, BDK and others) so you can verify the product\'s kashrut before buying it. Kashrut laws establish different food categories: <strong>parve</strong> products (no meat or dairy) can be eaten with any meal; <strong>dairy</strong> products (chalav) cannot be mixed with meat; and <strong>meat</strong> products (basar) require a waiting period after dairy according to each community\'s tradition.',
    'categories_intro_3'     => 'Use each category\'s filters to narrow your search by country of origin, brand or certifier. If you\'re looking for a specific product, you can use the name search or scan the barcode with your device\'s camera.',
    'categories_faq_heading' => 'Frequently Asked Questions about Kosher Categories',
    'categories_faq_1_q'     => 'What is the difference between parve, dairy and meat?',
    'categories_faq_1_a'     => 'Kashrut divides food into three main groups. <strong>Parve</strong> products contain no meat or dairy (they include fruits, vegetables, eggs, fish and most grains) and can be eaten with any meal. <strong>Dairy</strong> products contain milk or its derivatives and cannot be mixed with or eaten alongside meat according to kashrut laws. <strong>Meat</strong> products come from permitted animals slaughtered according to shechita rules and require a waiting period after dairy that varies between communities (between 1 and 6 hours).',
    'categories_faq_2_q'     => 'Can I trust an imported product without a local kosher seal?',
    'categories_faq_2_a'     => 'It depends on the seal it carries. A product with OU (Orthodox Union), OK Kosher, Star-K or Kof-K is internationally recognized and accepted by practically all Jewish communities. If the seal is from a regional certifier unknown in your country, it\'s advisable to consult your rabbi or local kosher authority before consuming it. KosherMap shows each product\'s certifier to help you make that decision.',
    'categories_faq_3_q'     => 'Do cleaning or cosmetic products need kosher certification?',
    'categories_faq_3_a'     => 'In general, non-food products don\'t require kosher certification for everyday use. However, some products that come into contact with the mouth (toothpaste, mouthwash, lipstick) or are used in food preparation (hand soap, detergent) may need supervision, especially during Passover, when restrictions are stricter. Consult your rabbinic authority if you have specific questions.',

    'certifiers_title'       => 'Kosher Certifiers - KosherMap',
    'certifiers_description' => 'Learn about the world\'s leading kosher certifiers featured on KosherMap: Orthodox Union (OU), KMD Mexico, Ajdut Kosher, BDK Brasil, Chile Kosher, Kehila Uruguay and more.',
    'certifiers_intro_1'     => 'A kosher certification is the endorsement of a rabbinical agency guaranteeing that a product complies with the laws of kashrut (Jewish dietary law). Without this seal, a product cannot be considered kosher even if its ingredients seem acceptable, since certification also involves supervision of the production process, line cleaning, and separation of meat and dairy.',
    'certifiers_intro_2'     => 'KosherMap includes products certified by the most recognized agencies in Latin America, the United States, and Israel: the <strong>Orthodox Union (OU)</strong> — the largest in the world, present in supermarkets in over 100 countries — <strong>KMD Mexico</strong>, <strong>Ajdut Kosher Argentina</strong>, <strong>BDK Brasil</strong>, <strong>Chile Kosher (CK)</strong>, <strong>Kehila Uruguay</strong>, and <strong>UK Kosher Latin America</strong>, among others.',
    'certifiers_intro_3'     => 'Click on a certifier to see all its products available in the directory. You can filter results by food category (dairy, meat, beverages, bakery, etc.) to find exactly what you need.',
    'certifiers_faq_heading' => 'Frequently Asked Questions about Kosher Certifiers',
    'certifiers_faq_1_q'     => 'What is the Orthodox Union (OU) and why is it so well recognized?',
    'certifiers_faq_1_a'     => 'The Orthodox Union is the largest kosher certification agency in the world, based in New York. It supervises over a million products in more than 100 countries. Its seal — a U inside a circle — is accepted by practically all Orthodox, Conservative, and Reform Jewish communities worldwide. OU-certified products are the easiest to find in international supermarkets and are the reference standard for kosher trade worldwide.',
    'certifiers_faq_2_q'     => 'Do all certifiers have the same level of kashrut?',
    'certifiers_faq_2_a'     => 'Not exactly. There are different levels of kosher supervision. The basic standard is regular kosher, supervised by a recognized agency. The <strong>Mehadrin</strong> level involves stricter control at every step of production and is required by more observant communities. The <strong>Badatz</strong> level (mainly in Israel) is the most demanding. Each community and rabbi has their own preferences about which certifiers they accept. It\'s advisable to consult your local rabbinic authority if you have questions.',
    'certifiers_faq_3_q'     => 'Why do some products have more than one kosher seal?',
    'certifiers_faq_3_a'     => 'The same product may be certified by several agencies to serve different markets. A company that exports to Israel, the United States, and Argentina may need the Israeli Chief Rabbinate seal, OU for the North American market, and Ajdut Kosher for the Argentine market. Having multiple seals doesn\'t duplicate the product\'s kashrut; it simply expands the markets it can legally access as a certified kosher product.',
];
