<?php

return [
    'categories_title'       => 'Catégories d\'Aliments Kasher - KosherMap',
    'categories_description' => 'Explorez toutes les catégories d\'aliments kasher : produits laitiers, viandes, boissons, boulangerie, snacks et plus. Chaque catégorie inclut des produits certifiés par les principales agences kasher du monde.',
    'categories_intro_1'     => 'KosherMap organise son catalogue de plus de 6 000 produits kasher en catégories et sous-catégories pour faciliter votre recherche. Trouvez des aliments certifiés par catégorie : des produits laitiers et viandes à la boulangerie, boissons, snacks et produits d\'entretien.',
    'categories_intro_2'     => 'Chaque catégorie affiche le sceau de la certification (OU, KMD, Ajdut, BDK et autres) afin que vous puissiez vérifier la cacherout du produit avant de l\'acheter. Les lois de la cacherout établissent différentes catégories d\'aliments : les produits <strong>parve</strong> (sans viande ni produits laitiers) peuvent être consommés avec n\'importe quel repas ; les produits <strong>laitiers</strong> (chalav) ne peuvent pas être mélangés avec la viande ; et les produits <strong>carnés</strong> (basar) nécessitent un délai d\'attente après les produits laitiers, variable selon la tradition de chaque communauté.',
    'categories_intro_3'     => 'Utilisez les filtres de chaque catégorie pour affiner votre recherche par pays d\'origine, marque ou certificateur. Si vous cherchez un produit spécifique, vous pouvez utiliser la recherche par nom ou scanner le code-barres avec la caméra de votre appareil.',
    'categories_faq_heading' => 'Questions fréquentes sur les catégories kasher',
    'categories_faq_1_q'     => 'Quelle est la différence entre parve, laitier et carné ?',
    'categories_faq_1_a'     => 'La cacherout divise les aliments en trois grands groupes. Les produits <strong>parve</strong> ne contiennent ni viande ni produits laitiers (fruits, légumes, œufs, poisson et la plupart des céréales) et peuvent être consommés avec n\'importe quel repas. Les produits <strong>laitiers</strong> contiennent du lait ou ses dérivés et ne peuvent pas être mélangés ni consommés avec de la viande selon les lois de la cacherout. Les produits <strong>carnés</strong> proviennent d\'animaux autorisés abattus selon les règles de la schehita et nécessitent un délai d\'attente après les produits laitiers qui varie selon les communautés (entre 1 et 6 heures).',
    'categories_faq_2_q'     => 'Puis-je faire confiance à un produit importé sans sceau kasher local ?',
    'categories_faq_2_a'     => 'Cela dépend du sceau qu\'il porte. Un produit portant OU (Orthodox Union), OK Kosher, Star-K ou Kof-K est reconnu internationalement et accepté par pratiquement toutes les communautés juives. Si le sceau provient d\'un certificateur régional inconnu dans votre pays, il est recommandé de consulter votre rabbin ou autorité kasher locale avant de le consommer. KosherMap affiche le certificateur de chaque produit pour vous aider à prendre cette décision.',
    'categories_faq_3_q'     => 'Les produits d\'entretien ou cosmétiques nécessitent-ils une certification kasher ?',
    'categories_faq_3_a'     => 'En général, les produits non alimentaires ne nécessitent pas de certification kasher pour un usage quotidien. Cependant, certains produits en contact avec la bouche (dentifrice, bain de bouche, rouge à lèvres) ou utilisés dans la préparation des aliments (savon pour les mains, détergent) peuvent nécessiter une supervision, en particulier pendant Pessah, lorsque les restrictions sont plus strictes. Consultez votre autorité rabbinique pour toute question spécifique.',
];
