<?php

return [
    'categories_title'       => 'Catégories d\'Aliments Kasher - KosherMap',
    'categories_description' => 'Explorez toutes les catégories d\'aliments kasher : produits laitiers, viandes, boissons, boulangerie, snacks et plus. Chaque catégorie inclut des produits certifiés par les principales agences kasher du monde.',
    'categories_intro_1'     => 'KosherMap organise son catalogue de plus de 6 000 produits kasher en catégories et sous-catégories pour faciliter votre recherche. Trouvez des aliments certifiés par catégorie : des produits laitiers et viandes à la boulangerie, boissons, snacks et produits d\'entretien.',
    'categories_intro_2'     => 'Chaque catégorie affiche le sceau de la certification (OU, KMD, Ajdut, BDK et autres) afin que vous puissiez vérifier la cacherout du produit avant de l\'acheter. Les lois de la cacherout établissent différentes catégories d\'aliments : les produits <strong>parve</strong> (sans viande ni produits laitiers) peuvent être consommés avec n\'importe quel repas ; les produits <strong>laitiers</strong> (chalav) ne peuvent pas être mélangés avec la viande ; et les produits <strong>carnés</strong> (basar) nécessitent un délai d\'attente après les produits laitiers, variable selon la tradition de chaque communauté.',
    'categories_intro_3'     => 'Utilisez les filtres de chaque catégorie pour affiner votre recherche par pays d\'origine, marque ou certificateur. Si vous cherchez un produit spécifique, vous pouvez utiliser la recherche par nom ou scanner le code-barres avec la caméra de votre appareil.',
    'categories_faq_heading' => 'Questions fréquentes sur les catégories kasher',
    'categories_faq_1_q'     => 'Quelle est la différence entre parve, laitier et carné ?',
    'categories_faq_1_a'     => 'La cacherout divise les aliments en trois grands groupes. Les produits <strong>parve</strong> ne contiennent ni viande ni produits laitiers (fruits, légumes, œufs, poisson et la plupart des céréales) et peuvent être consommés avec n\'importe quel repas. Les produits <strong>laitiers</strong> contiennent du lait ou ses dérivés et ne peuvent pas être mélangés ni consommés avec de la viande selon les lois de la cacherout. Les produits <strong>carnés</strong> proviennent d\'animaux autorisés abattus selon les règles de la schehita et nécessitent un délai d\'attente après les produits laitiers qui varie selon les communautés (entre 1 et 6 heures).',
    'categories_faq_2_q'     => 'Puis-je faire confiance à un produit importé sans sceau kasher local ?',
    'categories_faq_2_a'     => 'Cela dépend du sceau qu\'il porte. Un produit portant OU (Orthodox Union), OK Kosher, Star-K ou Kof-K est reconnu internationalement et accepté par pratiquement toutes les communautés juives. Si le sceau provient d\'un certificateur régional inconnu dans votre pays, il est recommandé de consulter votre rabbin ou autorité kasher locale avant de le consommer. KosherMap affiche le certificateur de chaque produit pour vous aider à prendre cette décision.',
    'categories_faq_3_q'     => 'Les produits d\'entretien ou cosmétiques nécessitent-ils une certification kasher ?',
    'categories_faq_3_a'     => 'En général, les produits non alimentaires ne nécessitent pas de certification kasher pour un usage quotidien. Cependant, certains produits en contact avec la bouche (dentifrice, bain de bouche, rouge à lèvres) ou utilisés dans la préparation des aliments (savon pour les mains, détergent) peuvent nécessiter une supervision, en particulier pendant Pessah, lorsque les restrictions sont plus strictes. Consultez votre autorité rabbinique pour toute question spécifique.',

    'certifiers_title'       => 'Certificateurs Kasher - KosherMap',
    'certifiers_description' => 'Découvrez les principaux certificateurs kasher du monde présents sur KosherMap : Orthodox Union (OU), KMD Mexique, Ajdut Kosher, BDK Brésil, Chile Kosher, Kehila Uruguay et plus.',
    'certifiers_intro_1'     => 'Une certification kasher est l\'aval d\'une agence rabbinique garantissant qu\'un produit respecte les lois de la cacherout (alimentation juive). Sans ce sceau, un produit ne peut pas être considéré comme cachère même si ses ingrédients semblent acceptables, car la certification implique aussi la supervision du processus de production, le nettoyage des lignes et la séparation de la viande et des produits laitiers.',
    'certifiers_intro_2'     => 'KosherMap inclut des produits certifiés par les agences les plus reconnues d\'Amérique latine, des États-Unis et d\'Israël : l\'<strong>Orthodox Union (OU)</strong> — la plus grande au monde, présente dans les supermarchés de plus de 100 pays —, <strong>KMD Mexique</strong>, <strong>Ajdut Kosher Argentine</strong>, <strong>BDK Brésil</strong>, <strong>Chile Kosher (CK)</strong>, <strong>Kehila Uruguay</strong> et <strong>UK Kosher Amérique Latine</strong>, entre autres.',
    'certifiers_intro_3'     => 'Cliquez sur un certificateur pour voir tous ses produits disponibles dans le répertoire. Vous pouvez filtrer les résultats par catégorie d\'aliment (produits laitiers, viandes, boissons, boulangerie, etc.) pour trouver exactement ce dont vous avez besoin.',
    'certifiers_faq_heading' => 'Questions fréquentes sur les certificateurs kasher',
    'certifiers_faq_1_q'     => 'Qu\'est-ce que l\'Orthodox Union (OU) et pourquoi est-elle si reconnue ?',
    'certifiers_faq_1_a'     => 'L\'Orthodox Union est la plus grande agence de certification kasher au monde, basée à New York. Elle supervise plus d\'un million de produits dans plus de 100 pays. Son sceau — un U dans un cercle — est accepté par pratiquement toutes les communautés juives orthodoxes, conservatrices et réformées à travers le monde. Les produits OU sont les plus faciles à trouver dans les supermarchés internationaux et constituent la norme de référence pour le commerce kasher mondial.',
    'certifiers_faq_2_q'     => 'Tous les certificateurs ont-ils le même niveau de cacherout ?',
    'certifiers_faq_2_a'     => 'Pas exactement. Il existe différents niveaux de supervision cachère. La norme de base est le kasher régulier, supervisé par une agence reconnue. Le niveau <strong>Mehadrin</strong> implique un contrôle plus strict à chaque étape de la production et est exigé par les communautés plus observantes. Le niveau <strong>Badatz</strong> (principalement en Israël) est le plus exigeant. Chaque communauté et chaque rabbin a ses propres préférences quant aux certificateurs qu\'il accepte. Il est conseillé de consulter votre autorité rabbinique locale en cas de doute.',
    'certifiers_faq_3_q'     => 'Pourquoi certains produits ont-ils plus d\'un sceau kasher ?',
    'certifiers_faq_3_a'     => 'Un même produit peut être certifié par plusieurs agences pour répondre à différents marchés. Une entreprise qui exporte vers Israël, les États-Unis et l\'Argentine peut avoir besoin du sceau du Grand Rabbinat israélien, de l\'OU pour le marché nord-américain et d\'Ajdut Kosher pour le marché argentin. Avoir plusieurs sceaux ne duplique pas la cacherout du produit ; cela élargit simplement les marchés auxquels il peut accéder légalement en tant que produit cachère certifié.',
];
