<?php

return [
    'categories_title'       => 'Rubros de Alimentos Kosher - KosherMap',
    'categories_description' => 'Explorá todas las categorías de alimentos kosher: lácteos, carnes, bebidas, panadería, snacks y más. Cada rubro incluye productos certificados por las principales agencias kosher del mundo.',
    'categories_intro_1'     => 'KosherMap organiza su catálogo de más de 6.000 productos kosher en rubros y subrubros para facilitar tu búsqueda. Encontrá alimentos certificados por categoría: desde lácteos y carnes hasta panadería, bebidas, snacks y productos de limpieza.',
    'categories_intro_2'     => 'Cada categoría muestra el sello de la certificadora (OU, KMD, Ajdut, BDK y otras) para que puedas verificar la kashrut del producto antes de comprarlo. Las leyes de kashrut establecen distintas categorías para los alimentos: los productos <strong>parve</strong> (sin carne ni lácteos) pueden consumirse con cualquier comida; los <strong>lácteos</strong> (chalav) no pueden mezclarse con carne; y los productos <strong>cárnicos</strong> (basar) requieren una espera después de los lácteos según la tradición de cada comunidad.',
    'categories_intro_3'     => 'Usá los filtros de cada categoría para acotar tu búsqueda por país de origen, marca o certificadora. Si buscás un producto específico, podés usar el buscador por nombre o escanear el código de barras con la cámara de tu dispositivo.',
    'categories_faq_heading' => 'Preguntas frecuentes sobre rubros kosher',
    'categories_faq_1_q'     => '¿Qué diferencia hay entre parve, lácteo y cárnico?',
    'categories_faq_1_a'     => 'La kashrut divide los alimentos en tres grandes grupos. Los productos <strong>parve</strong> no contienen carne ni lácteos (incluyen frutas, verduras, huevos, pescado y la mayoría de los granos) y pueden comerse con cualquier comida. Los productos <strong>lácteos</strong> contienen leche o derivados y no pueden mezclarse con carne ni consumirse juntos según las leyes de kashrut. Los productos <strong>cárnicos</strong> provienen de animales permitidos sacrificados según las reglas de shejitá y requieren una separación temporal de los lácteos que varía entre comunidades (entre 1 y 6 horas).',
    'categories_faq_2_q'     => '¿Puedo confiar en un producto importado sin sello kosher local?',
    'categories_faq_2_a'     => 'Depende del sello que tenga. Un producto con OU (Orthodox Union), OK Kosher, Star-K o Kof-K es reconocido internacionalmente y aceptado por prácticamente todas las comunidades judías. Si el sello es de una certificadora regional desconocida en tu país, es recomendable consultar con tu rabino o autoridad kosher local antes de consumirlo. KosherMap muestra la certificadora de cada producto para ayudarte a tomar esa decisión.',
    'categories_faq_3_q'     => '¿Los productos de limpieza o cosméticos necesitan certificación kosher?',
    'categories_faq_3_a'     => 'En general, los productos no comestibles no requieren certificación kosher para uso cotidiano. Sin embargo, algunos productos que entran en contacto con la boca (pasta de dientes, enjuague bucal, lápiz labial) o que se usan en la preparación de alimentos (jabón de manos, detergente) pueden necesitar supervisión, especialmente durante Pesaj, cuando las restricciones son más estrictas. Consultá con tu autoridad rabínica si tenés dudas específicas.',

    'certifiers_title'       => 'Certificadoras Kosher - KosherMap',
    'certifiers_description' => 'Conocé las principales certificadoras kosher del mundo presentes en KosherMap: Orthodox Union (OU), KMD México, Ajdut Kosher, BDK Brasil, Chile Kosher, Kehila Uruguay y más.',
    'certifiers_intro_1'     => 'Una certificación kosher es el aval de una agencia rabínica que garantiza que un producto cumple con las leyes de kashrut (alimentación judía). Sin este sello, un producto no puede considerarse kosher aunque sus ingredientes parezcan aceptables, ya que la certificación también implica supervisión del proceso de producción, limpieza de líneas y separación de carne y lácteos.',
    'certifiers_intro_2'     => 'KosherMap incluye productos certificados por las agencias más reconocidas de América Latina, Estados Unidos e Israel: la <strong>Orthodox Union (OU)</strong> —la más grande del mundo, con presencia en supermercados de más de 100 países—, <strong>KMD México</strong>, <strong>Ajdut Kosher Argentina</strong>, <strong>BDK Brasil</strong>, <strong>Chile Kosher (CK)</strong>, <strong>Kehila Uruguay</strong> y <strong>UK Kosher Latinoamérica</strong>, entre otras.',
    'certifiers_intro_3'     => 'Hacé click en una certificadora para ver todos sus productos disponibles en el directorio. Podés filtrar los resultados por categoría de alimento (lácteos, carnes, bebidas, panadería, etc.) para encontrar exactamente lo que necesitás.',
    'certifiers_faq_heading' => 'Preguntas frecuentes sobre certificadoras kosher',
    'certifiers_faq_1_q'     => '¿Qué es la Orthodox Union (OU) y por qué es tan reconocida?',
    'certifiers_faq_1_a'     => 'La Orthodox Union es la agencia de certificación kosher más grande del mundo, con sede en Nueva York. Supervisa más de un millón de productos en más de 100 países. Su sello —una U dentro de un círculo— es aceptado por prácticamente todas las comunidades judías ortodoxas, conservadoras y reformistas a nivel global. Los productos con OU son los más fáciles de encontrar en supermercados internacionales y son el estándar de referencia para el comercio kosher mundial.',
    'certifiers_faq_2_q'     => '¿Todas las certificadoras tienen el mismo nivel de kashrut?',
    'certifiers_faq_2_a'     => 'No exactamente. Hay distintos niveles de supervisión kasher. El estándar básico es el kosher regular, supervisado por una agencia reconocida. El nivel <strong>Mehadrin</strong> implica un control más estricto en todos los pasos de producción y es requerido por comunidades más observantes. El nivel <strong>Badatz</strong> (principalmente en Israel) es el más exigente. Cada comunidad y cada rabino tiene sus propias preferencias sobre qué certificadoras acepta. Es recomendable consultar con tu autoridad rabínica local si tenés dudas.',
    'certifiers_faq_3_q'     => '¿Por qué algunos productos tienen más de un sello kosher?',
    'certifiers_faq_3_a'     => 'Un mismo producto puede estar certificado por varias agencias para satisfacer distintos mercados. Una empresa que exporta a Israel, Estados Unidos y Argentina puede necesitar el sello del Gran Rabinato israelí, el OU para el mercado norteamericano y Ajdut Kosher para el mercado argentino. Tener múltiples sellos no duplica la kashrut del producto; simplemente amplía los mercados a los que puede acceder legalmente como producto kosher certificado.',
];
