<?php

return [
    'categories_title'       => 'Rubros de Alimentos Kosher - KosherMap',
    'categories_description' => 'Explorá todas las categorías de alimentos kosher: lácteos, carnes, bebidas, panadería, snacks y más. Cada rubro incluye productos certificados por las principales agencias kosher del mundo.',
    'categories_intro_1'     => 'KosherMap organiza su catálogo de más de 6.000 productos kosher en rubros y subrubros para facilitar tu búsqueda. Encontrá alimentos certificados por categoría: desde lácteos y carnes hasta panadería, bebidas, snacks y productos de limpieza.',
    'categories_intro_2'     => 'Cada categoría muestra el sello de la certificadora (OU, KMD, Ajdut, BDK y otras) para que puedas verificar la kashrut del producto antes de comprarlo. Las leyes de kashrut establecen distintas categorías para los alimentos: los productos <strong>parve</strong> (sin carne ni lácteos) pueden consumirse con cualquier comida; los <strong>lácteos</strong> (chalav) no pueden mezclarse con carne; y los productos <strong>cárnicos</strong> (basar) requieren una espera después de los lácteos según la tradición de cada comunidad.',
    'categories_intro_3'     => 'Usá los filtros de cada categoría para acotar tu búsqueda por país de origen, marca o certificadora. Si buscás un producto específico, podés usar el buscador por nombre o escanear el código de barras con la cámara de tu dispositivo.',
    'categories_faq_heading' => 'Preguntas frecuentes sobre rubros kosher',
    'categories_faq_1_q'     => '¿Qué diferencia hay entre parve, lácteo y cárnico?',
    'categories_faq_1_a'     => 'La kashrut divide los alimentos en tres grandes grupos. Los productos <strong>parve</strong> no contienen carne ni lácteos (incluyen frutas, verduras, huevos, pescado y la mayoría de los granos) y pueden comerse con cualquier comida. Los productos <strong>lácteos</strong> contienen leche o derivados y no pueden mezclarse con carne ni consumirse juntos según las leyes de kashrut. Los productos <strong>cárnicos</strong> provienen de animales permitidos sacrificados según las reglas de shejitá y requieren una separación temporal de los lácteos que varía entre comunidades (entre 1 y 6 horas).',
    'categories_faq_2_q'     => '¿Puedo confiar en un producto importado sin sello kosher local?',
    'categories_faq_2_a'     => 'Depende del sello que tenga. Un producto con OU (Orthodox Union), OK Kosher, Star-K o Kof-K es reconocido internacionalmente y aceptado por prácticamente todas las comunidades judías. Si el sello es de una certificadora regional desconocida en tu país, es recomendable consultar con tu rabino o autoridad kosher local antes de consumirlo. KosherMap muestra la certificadora de cada producto para ayudarte a tomar esa decisión.',
    'categories_faq_3_q'     => '¿Los productos de limpieza o cosméticos necesitan certificación kosher?',
    'categories_faq_3_a'     => 'En general, los productos no comestibles no requieren certificación kosher para uso cotidiano. Sin embargo, algunos productos que entran en contacto con la boca (pasta de dientes, enjuague bucal, lápiz labial) o que se usan en la preparación de alimentos (jabón de manos, detergente) pueden necesitar supervisión, especialmente durante Pesaj, cuando las restricciones son más estrictas. Consultá con tu autoridad rabínica si tenés dudas específicas.',
];
